    <header>
        <nav class="nav_bar">
            <div class="Logo_nav">
                <img src="/images/World_Amphoreus.jpg" alt="Ampho logo" class="logo">
                <h2>Amphoreus - The Eternal Land</h2>
            </div>
            <ul class="menu">
                <li><a href="index.html">Home</a></li>
                <li><a href="about.html">About</a></li>
                <li><a href="jobs.html">Jobs</a></li>
                <li><a href="apply.html">Apply</a></li>
                <li><a href="mailto:info@Amphoreus.com.au">Email Us</a></li>
            </ul>
        </nav>
    </header>